--ORTALAMA TESLIMAT SURESI
select 
U.ID,U.NAMESURNAME,
avg(DATEDIFF(hour,O.DATE_,I.DATE_)) ORTALAMATESLIMAT_SURESI,
MIN(DATEDIFF(hour,O.DATE_,I.DATE_)) ENKISA_TESLIMAT_SURESI,
MAX(DATEDIFF(hour,O.DATE_,I.DATE_)) ENUZUN_TESLIMAT_SURESI,
SUM(O.TOTALPRICE) AS TOPLAM_SIPARIS_TUTARI,
COUNT(O.ID) AS SIPARIS_SAYISI

from ORDERS as O
	inner join USERS U on O.USERID= U.ID
	inner join ADDRESS A ON A.ID= O.ADDRESSID
	inner join CITIES CT ON CT.ID = A.CITYID
	inner join TOWNS T ON T.ID = A.TOWNID
	inner join DISTRICTS D on D.ID = A.DISTRICTID
	inner join PAYMENTS P ON P.ORDERID = O.ID 
	inner join INVOICES I ON I.ORDERID = O.ID

GROUP BY U.ID,U.NAMESURNAME
HAVING avg(DATEDIFF(hour,O.DATE_,I.DATE_))>25
order by 6 desc 
