--TARIHE GORE SIPARIS DAGILIMINI GETIREN SORGU

select
CONVERT(date,O.DATE_) TARIH,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTAR,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI
from ORDERS as O
	inner join USERS U on O.USERID= U.ID
	inner join ADDRESS A ON A.ID= O.ADDRESSID
	inner join CITIES CT ON CT.ID = A.CITYID
	inner join TOWNS T ON T.ID = A.TOWNID
	inner join DISTRICTS D on D.ID = A.DISTRICTID
	inner join PAYMENTS P ON P.ORDERID = O.ID 
	inner join INVOICES I ON I.ORDERID = O.ID
	inner join ORDERDETAILS OD ON OD.ORDERID = O.ID
	inner join ITEMS ITM on ITM.ID = OD.ITEMID
GROUP BY CONVERT(date,O.DATE_)
ORDER BY CONVERT(date,O.DATE_)