--URUN KATEGORILERINE GORE SIPARIS DAGILIMI
select 
ITM.CATEGORY1, ITM.CATEGORY2, ITM.CATEGORY3,
SUM(OD.LINETOTAL) TOPLAMSIPARIS_TUTARI,
sum(OD.AMOUNT) TOPLAMSIPARIS_ADEDI,
COUNT(OD.ID) TOPLAMSIPARIS_SAYISI,
SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) AS ORTALAMABIRIMFIYAT
from ORDERS as O
	inner join USERS U on O.USERID= U.ID
	inner join ADDRESS A ON A.ID= O.ADDRESSID
	inner join CITIES CT ON CT.ID = A.CITYID
	inner join TOWNS T ON T.ID = A.TOWNID
	inner join DISTRICTS D on D.ID = A.DISTRICTID
	inner join PAYMENTS P ON P.ORDERID = O.ID 
	inner join INVOICES I ON I.ORDERID = O.ID
	inner join ORDERDETAILS OD ON OD.ORDERID = O.ID
	inner join ITEMS ITM on ITM.ID = OD.ITEMID
	--WHERE ITM.CATEGORY1='KOZMETIK'
GROUP BY ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3
ORDER BY 4 DESC