--ORTALAMA TESLIMAT SURESI
select 
--O.ID AS SIPARISID,
--O.DATE_ AS SIPARISTARIHI,
--I.DATE_ AS FATURATARIHI,
MIN(DATEDIFF(hour,O.DATE_,I.DATE_)) as ENKISA_TESLIMATSURESI_SAAT,
MAX(DATEDIFF(hour,O.DATE_,I.DATE_)) as ENUZUN_TESLIMATSURESI_SAAT,
avg(DATEDIFF(hour,O.DATE_,I.DATE_)) as ORTALAMA_TESLIMATSURESI_SAAT

from ORDERS as O
	inner join USERS U on O.USERID= U.ID
	inner join ADDRESS A ON A.ID= O.ADDRESSID
	inner join CITIES CT ON CT.ID = A.CITYID
	inner join TOWNS T ON T.ID = A.TOWNID
	inner join DISTRICTS D on D.ID = A.DISTRICTID
	inner join PAYMENTS P ON P.ORDERID = O.ID 
	inner join INVOICES I ON I.ORDERID = O.ID
