--Þehirlere göre toplam verilen sipariþ miktarlarý

select 
CT.CITY SEHIRADI,
SUM(OD.LINETOTAL) TOPLAMSIPARIS_TUTARI,
sum(OD.AMOUNT) TOPLAMSIPARIS_ADEDI,
COUNT(OD.ID) TOPLAMSIPARIS_SAYISI
from ORDERS as O
	inner join USERS U on O.USERID= U.ID
	inner join ADDRESS A ON A.ID= O.ADDRESSID
	inner join CITIES CT ON CT.ID = A.CITYID
	inner join TOWNS T ON T.ID = A.TOWNID
	inner join DISTRICTS D on D.ID = A.DISTRICTID
	inner join PAYMENTS P ON P.ORDERID = O.ID 
	inner join INVOICES I ON I.ORDERID = O.ID
	inner join ORDERDETAILS OD ON OD.ORDERID = O.ID
	inner join ITEMS ITM on ITM.ID = OD.ITEMID
GROUP BY CT.CITY
ORDER BY CT.CITY